CREATE SET TABLE Informatica_Test.BatchControl ,FALLBACK ,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    MAP = TD_MAP1
    (
    BatchControlID INTEGER GENERATED ALWAYS AS IDENTITY
    (START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1 
    MAXVALUE 2147483647 
    NO CYCLE),
    BatchID INTEGER,
    LoadWindowStartDate TIMESTAMP(6),
    LoadWindowEndDate TIMESTAMP(6),
    StartDatetime TIMESTAMP(6),
    EndDatetime TIMESTAMP(6),
    Status VARCHAR(8) CHARACTER SET LATIN CASESPECIFIC,
    ErrorMessage VARCHAR(1000) CHARACTER SET LATIN CASESPECIFIC)
    UNIQUE PRIMARY INDEX ( BatchControlID );